/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.IndividualReceiverOrganizationAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.TableColors;
import javax.swing.JPanel;

/**
 *
 * @author KNN Team
 */
public class IndividualReceiverWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndividualReceiverWorkAreaJPanel
     */
    public IndividualReceiverWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network, EcoSystem business) {
        initComponents();
        individualReceiverOrganizationJTable.getTableHeader().setDefaultRenderer(new TableColors());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        individualReceiverOrganizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orgLocation = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        orgLocation1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        individualReceiverOrganizationJTable.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        individualReceiverOrganizationJTable.setForeground(new java.awt.Color(25, 56, 82));
        individualReceiverOrganizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Order request Time", "Order Delivery Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        individualReceiverOrganizationJTable.setSelectionBackground(new java.awt.Color(56, 90, 174));
        jScrollPane1.setViewportView(individualReceiverOrganizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 111, 581, 157));

        addJButton.setBackground(new java.awt.Color(255, 255, 255));
        addJButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addJButton.setForeground(new java.awt.Color(25, 56, 82));
        addJButton.setText("Submit");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 56, 82));
        jLabel3.setText("Email ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 56, 82));
        jLabel2.setText("Contact Number");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        orgLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgLocationActionPerformed(evt);
            }
        });
        add(orgLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 230, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 56, 82));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MANAGE INDIVIDUAL RECEIVER ORGANIZATION");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 34, 581, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 56, 82));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        orgLocation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgLocation1ActionPerformed(evt);
            }
        });
        add(orgLocation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

//        Type type = (Type) organizationJComboBox.getSelectedItem();
//
//        if("".equals(orgNameTextField.getText())) {
//            JOptionPane.showMessageDialog(null, "Enter organization name!");
//        }else if("".equals(orgLocation.getText())) {
//            JOptionPane.showMessageDialog(null, "Please set a location");
//        }else {
//            locationPoint = orgLocation.getText();
//            Organization organization = directory.createOrganization(type,orgNameTextField.getText(), locationPoint);
//            JOptionPane.showMessageDialog(null, "Organization Successfully Created");
//
//            populateTable();
//            resetFields();
//        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void orgLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgLocationActionPerformed

    private void orgLocation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgLocation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgLocation1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTable individualReceiverOrganizationJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orgLocation;
    private javax.swing.JTextField orgLocation1;
    // End of variables declaration//GEN-END:variables
}
